# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - jdk12

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту dunor@mail.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -dunor@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
env:
  global:
    - CODECOV_TOKEN="9a0b06e4-8623-4923-8fb5-e1e51007f6ff"